name: Publish

on:
  push:
    branches:
    - main
#  schedule:
#    - cron:  '0 8 * * *'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.97.0'

    - name: Build
      run: hugo --minify

    - name: Build downloadable archive of website
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'public.zip'
        path: './public/'
        #exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Move downloadable archive to public
      run: mv public.zip ./public/cpweb-javascript.zip

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server:  ${{ secrets.DEPLOY_FTP_HOST }}
        username: ${{ secrets.DEPLOY_FTP_USERNAME }}
        password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
        server-dir: /
        local-dir: ./public/