name: Publish

on:
  push:
    branches:
    - main
#  schedule:
#    - cron:  '0 8 * * *'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.97.0'

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        ftp-server:  ${{ secrets.DEPLOY_FTP_HOST_PATH }}
        ftp-username: ${{ secrets.DEPLOY_FTP_USERNAME }}
        ftp-password: ${{ secrets.DEPLOY_FTP_PASSWORD }}
        local-dir: public/